# Generated by Django 4.1.1 on 2022-09-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('nbr_propositions', models.IntegerField()),
            ],
        ),
    ]
