# Generated by Django 4.1.1 on 2022-09-19 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0003_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='prediction',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='item_id',
            field=models.ManyToManyField(blank=True, to='medical.item'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user_id',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
